name: My Starter Workflow

on:

jobs:
 workflow_dispatch:
  call-reusable-workflow:
  strategy:
    matrix:
      nodeversion: [14, 16, 18, 20]
  uses: ./.github/workflows/reusable-workflow.yml
  with:
    node: ${{ matrix.nodeversion }}
  with:
   uses: ./.github/workflows/reusable-workflow.yml
  with:
    node: 14
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy to your project.
